#!/bin/bash

# The following script takes the following params:
#
# ./shuffle a b in_file out_file
#
# It takes in_file, scrambles lines a through b inclusive, and writes this
# partially scrambled file to out_file.
#
# Note that for especially large files, this script should not be run from
# your home directory if there are quotas.
#
# For a file like sorted_2x10.sql, the following command would work:
# ./shuffle 100 20000099 sorted_2x10.sql unsorted_2x10.sql
#

echo "Calculating initial params..."
line_count=`wc -l $3 | cut -f1 -d' '`

head_param=`expr $1 - 1`
tail_param=`expr $line_count - $2`

echo "Creating head..."
head -n $head_param $3 > a

echo "Creating mid..."
sed -n "$1,$2p" $3 | shuf > b

echo "Creating tail..."
tail -n $tail_param $3 > c

echo "Concatenating files..."
cat a b c > $4
rm a b c
